- hosts: local
  user: vagrant
  sudo: yes
  tasks:
  - name: apt install
    apt:  name={{ item }} update_cache=yes
    with_items:
      - tmux
      - vim
      - nginx
      - openjdk-7-jdk
      - build-essential
      - nkf
      - jq
  - name: pip install
    pip:  name={{ item }}
    with_items:
      - fabric
      - awscli
  - name: install scala
    include: scala.yml

  - name: install ruby
    include: ruby.yml

  - name: install gem
    include: gem.yml

  - name: install zsh
    include: zsh.yml

  - name: install mysql
    include: mysql.yml

  - name: install docker
    include: docker.yml
    tags: docker
